# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    trusted_hosts: 
        - '^127\.0\.0\.1$'
        - '^localhost$'
        - '^.+\.ngrok-free\.dev$'
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session:
        enabled: true
        storage_factory_id: session.storage.factory.native
        cookie_samesite: none
        cookie_secure: true

when@dev:
    framework:
        session:
            cookie_samesite: lax
            cookie_secure: auto

    #esi: true
    #fragments: true

when@prod:
    framework:
        trusted_proxies: 'private_ranges'
        trusted_headers: ['x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port']
        trusted_hosts:
            - '^127\.0\.0\.1$'
            - '^localhost$'
            - '^.+\.up\.railway\.app$'
            - '^.+\.railway\.app$'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
